name: Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Ensure branch is up-to-date with main
        run: |
          git fetch origin main
          git diff --exit-code origin/main
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build
